# Generated by Django 4.0.5 on 2022-06-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('open_value', models.FloatField()),
                ('low_value', models.FloatField()),
                ('high_value', models.FloatField()),
                ('close_value', models.FloatField()),
                ('volume', models.IntegerField()),
                ('dt_time', models.DateTimeField()),
                ('interval', models.CharField(max_length=7)),
            ],
        ),
    ]
