# Generated by Django 4.0.5 on 2022-07-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_rename_stocksdomain_stockdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_close_limit', models.FloatField()),
                ('lower_close_limit', models.FloatField()),
                ('was_triggered', models.BooleanField(default=False)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_app.stocktracker')),
            ],
        ),
    ]
