# Generated by Django 4.0.5 on 2022-07-06 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0005_remove_stocktrigger_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktrigger',
            name='stock_tracker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker_app.stockdomain'),
        ),
    ]
